server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: trendscope-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/trends/**, /api/auth/**
        - id: external-data-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/external/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
