server:
  port: 8081

spring:
  application:
    name: external-data-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.trendscope: DEBUG
