server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: trendscope-microservice
ECHO est  desactivado.
  datasource:
    url: jdbc:mysql://localhost:3306/trendscope_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
ECHO est  desactivado.
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: myVerySecretKeyForTrendScopeApplication123456
  expiration: 86400000

logging:
  level:
    com.trendscope: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%%d{yyyy-MM-dd HH:mm:ss} - %%msg%%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
