server:
  port: 8080

spring:
  application:
    name: trendscope-microservice
  datasource:
    url: jdbc:mysql://mysql:3306/trendscope_db?useSSL=false&serverTimezone=UTC
    username: trendscope
    password: trendscope123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: redis
    port: 6379
    timeout: 2000ms

jwt:
  secret: trendscope-secret-key-2024
  expiration: 86400000

logging:
  level:
    com.trendscope: DEBUG
    org.springframework.security: DEBUG